# This workflow will build a Node Express app
name: cicd-pr

on:
  pull_request:
    branches: [main]

permissions:
  pull-requests: read

jobs:
  code-analysis:
    runs-on: ubuntu-latest
    steps:
      - name: Analyze with SonarCloud
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args:
            -Dsonar.projectKey=onFilm_node-express-rest-api
            -Dsonar.organization=prajwalacharya
            # Comma-separated paths to directories containing main source files.
            #-Dsonar.sources= # optional, default is project base directory
            # When you need the analysis to take place in a directory other than the one from which it was launched
            #-Dsonar.projectBaseDir= # optional, default is .
            # Comma-separated paths to directories containing test source files.
            #-Dsonar.tests= # optional. For more info about Code Coverage, please refer to https://docs.sonarcloud.io/enriching/test-coverage/overview/
            # Adds more detail to both client and server-side analysis logs, activating DEBUG mode for the scanner, and adding client-side environment variables and system properties to the server-side log of analysis report processing.
            #-Dsonar.verbose= # optional, default is false
  build-test:
    runs-on: ubuntu-latest
    needs: [code-analysis]
    steps:
      - name: Git checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@master
        with:
          node-version: 16
      - name: Install dependencies
        run: npm install
      - name: Run Tests
        run: npm test
  run-api-tests:
    runs-on: ubuntu-latest
    needs: [build-test]
    steps:
      - name: Git checkout
        uses: actions/checkout@v2
      - name: Create Docker Network
        run: docker network create local
      - name: Docker network
        run: docker network ls && docker network inspect local
      - name: Build node-rest-api-app docker container
        run: docker build -t image . && docker run -d -p 3001:3001 -v $(pwd):/src -v /src/node_modules --net local --name app image
      - name: Run API Tests
        run: docker run -d --net local --name rest-api-tests-app mail2prajwal12/rest-web-service-api-test
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: my-artifact
      - name: Display structure of downloaded files
        run: ls -R