name: node-express-rest-api-deploy
on:
  workflow_run:
    workflows: ["node-express-rest-api-ci-cd"]
    types:
      - completed
jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Deploy to Oracle Cloud via SSH action
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.ORACLE_HOST }}
          username: ${{ secrets.ORACLE_USERNAME }}
          key: ${{ secrets.ORACLE_PRIVATE_KEY }}
          port: 22
          script: |
            #!/bin/sh

            # Just run below command - ignore below command. [not working]
            # sudo docker rm $(sudo docker ps -a | grep node-express-rest-api-app | awk '{ print $1 }') -f

            # Stop running react-todolist Docker Containers
            sudo docker rm react-todolist-app -f

            # Free up space
            sudo docker system prune -a

            # Pull the Docker Image 
            sudo docker pull mail2prajwal12/node-express-rest-api:latest

            # Run a new container from a new image
            sudo docker run -d -p 3001:3001 -v $(pwd):/app -v /node_modules -e PORT=3001 --name node-express-rest-api-app mail2prajwal12/node-express-rest-api
